import test from 'node:test';import assert from 'node:assert/strict';
import {newSetup,effectiveRole,setupErrors,canAssign,draftOrder,tieGroups,handWinner,makeTies,uniformIndex,rollPlayer,rollAll,startDraft,advanceTie,finishTies,spinPool,beginSpin,finishSpin,editSetup,resultsText,parseSave,loadDraft,persistDraft,SAVE_KEY} from '../assets/draft.js';
function random(seed=1){return n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};}
function party(roles=['tank','healer','dps']){const s=newSetup();s.players=roles.map((role,i)=>({id:'p'+(i+1),name:'Friend '+(i+1),role,dice:20-i}));return s;}
function settled(s,r=random()){s=startDraft(s,r);return s.phase==='tiebreak'?finishTies(s):s;}
function brute(players,classes){if(!players.length)return true;return classes.some((c,i)=>c.enabled&&c.roles.includes(effectiveRole(players[0]))&&brute(players.slice(1),classes.filter((_,j)=>j!==i)));}
test('standard pools are nine unique classes; unassigned means DPS and experimental Shaman tank is off',()=>{const s=newSetup();assert.equal(s.classes.length,9);assert.deepEqual(s.classes.filter(c=>c.roles.includes('tank')).map(c=>c.name),['Warrior','Paladin','Druid']);assert.equal(s.classes.filter(c=>c.roles.includes('healer')).length,4);assert.equal(s.classes.filter(c=>c.roles.includes('dps')).length,9);assert.equal(effectiveRole({role:'unassigned'}),'dps');assert.equal(s.classes.find(c=>c.id==='shaman').roles.includes('tank'),false);});
test('random selection rejects biased overflow and checks invalid sources',()=>{const values=[0xffffffff,7];assert.equal(uniformIndex(3,()=>values.shift()),1);assert.throws(()=>uniformIndex(0));assert.throws(()=>uniformIndex(3,()=>-1));assert.equal(uniformIndex(1,()=>0xffffffff),0);});
test('per-person rolls and roll-all are bounded, immutable and unavailable after lock',()=>{const s=party();const one=rollPlayer(s,'p1',()=>0);assert.equal(one.players[0].dice,1);assert.equal(s.players[0].dice,20);assert.deepEqual(rollAll(s,()=>19).players.map(p=>p.dice),[20,20,20]);assert.throws(()=>rollPlayer(settled(s),'p1'));assert.throws(()=>rollAll(settled(s)));});
test('name, pool, role counts and missing rolls block invalid setups',()=>{let s=party();s.players[1].name=' friend 1 ';assert.match(setupErrors(s).join(' '),/different name/);s=party();s.players[0].name='';assert.match(setupErrors(s).join(' '),/needs a name/);s.players=[];assert.match(setupErrors(s).join(' '),/at least one player/);s=party(Array(10).fill('dps'));assert.match(setupErrors(s).join(' '),/only 9/);s=party(Array(4).fill('tank'));assert.match(setupErrors(s).join(' '),/only 3/);s=party();s.classes.forEach(c=>c.enabled=false);assert.match(setupErrors(s).join(' '),/Enable at least/);s=party();s.players[1].dice=null;assert.throws(()=>startDraft(s),/Roll a d20/);});
test('overlapping role capacity is detected beyond individual counts',()=>{const s=party(['tank','tank','healer','healer']);s.classes=[{id:'a',name:'A',enabled:true,roles:['tank','healer'],color:'#ffffff'},{id:'b',name:'B',enabled:true,roles:['tank','healer'],color:'#ffffff'},{id:'c',name:'C',enabled:true,roles:['dps'],color:'#ffffff'},{id:'d',name:'D',enabled:true,roles:['dps'],color:'#ffffff'}];assert.equal(canAssign(s.players,s.classes),false);assert.match(setupErrors(s).join(' '),/overlap/);assert.throws(()=>startDraft(s));});
test('role priority precedes dice, with descending dice inside each role',()=>{const s=party(['dps','healer','tank','tank','unassigned','healer']);s.players.forEach((p,i)=>p.dice=[20,19,1,15,18,2][i]);assert.deepEqual(draftOrder(s),['p4','p3','p2','p6','p1','p5']);});
test('lookahead keeps a later healer safe and explains the excluded tank class',()=>{const s=party(['tank','healer']);s.classes=s.classes.filter(c=>['warrior','paladin'].includes(c.id));const draft=settled(s),pool=spinPool(draft);assert.deepEqual(pool.safe.map(c=>c.id),['warrior']);assert.deepEqual(pool.excluded.map(c=>c.id),['paladin']);const next=finishSpin(beginSpin(draft,()=>0));assert.deepEqual(spinPool(next).safe.map(c=>c.id),['paladin']);});
test('every safe slice can be selected and the global pool never repeats a class',()=>{let s=settled(party(['dps','dps','dps']));const before=structuredClone(s);for(let i=0;i<spinPool(s).safe.length;i++){const pending=beginSpin(s,()=>i);assert.equal(pending.pending.classId,spinPool(s).safe[i].id);}assert.deepEqual(s,before);const first=beginSpin(s,()=>0);assert.throws(()=>beginSpin(first),/already/);s=finishSpin(first);assert.equal(s.picks.length,1);assert.equal(spinPool(s).safe.some(c=>c.id===s.picks[0].classId),false);assert.throws(()=>finishSpin(s),/No spin/);s=finishSpin(beginSpin(s,()=>0));s=finishSpin(beginSpin(s,()=>0));assert.equal(s.phase,'results');assert.equal(new Set(s.picks.map(p=>p.classId)).size,3);assert.throws(()=>beginSpin(s));assert.match(resultsText(s),/Friend 1/);});
test('all hand pairs implement paper-scissors-rock including draws',()=>{for(const h of ['rock','paper','scissors'])assert.equal(handWinner(h,h),null);for(const [a,b] of [['rock','scissors'],['scissors','paper'],['paper','rock']]){assert.equal(handWinner(a,b),'a');assert.equal(handWinner(b,a),'b');}assert.throws(()=>handWinner('fire','rock'));});
test('ties only join the same effective role and equal dice',()=>{const s=party(['tank','tank','healer','dps','unassigned','dps']);s.players.forEach((p,i)=>p.dice=i===5?12:16);assert.deepEqual(tieGroups(s).map(g=>g.ids),[['p1','p2'],['p4','p5']]);});
test('a draw repeats the same match before a settled winner; both players get ranks',()=>{const s=party(['dps','dps']);s.players.forEach(p=>p.dice=10);const values=[0,0,0,0,2];let draft=startDraft(s,()=>values.shift());assert.equal(draft.phase,'tiebreak');assert.equal(draft.ties.matches.length,2);assert.equal(draft.ties.matches[0].winnerId,null);assert.deepEqual(draft.ties.groups[0].ranking,['p2','p1']);draft=advanceTie(draft);assert.equal(draft.phase,'tiebreak');draft=advanceTie(draft);assert.equal(draft.phase,'drafting');assert.deepEqual(draft.queue,['p2','p1']);assert.throws(()=>advanceTie(draft));});
for(const count of [3,4,5,9])test(`a ${count}-player tie ranks everyone, including all losers`,()=>{const s=party(Array(count).fill('dps'));s.players.forEach(p=>p.dice=17);const draft=startDraft(s,random(count));const g=draft.ties.groups[0];assert.equal(g.ranking.length,count);assert.equal(new Set(g.ranking).size,count);assert.equal(g.brackets.length,count-1);assert.ok(g.brackets.slice(1).every((b,i)=>!b.seed.includes(g.ranking[i])));assert.equal(draft.ties.matches.filter(m=>m.winnerId).length,count*(count-1)/2);const done=finishTies(draft);assert.deepEqual(done.queue,g.ranking);assert.deepEqual(parseSave(JSON.stringify(done)),done);});
test('different tied groups preserve role and dice priority after their tournaments',()=>{const s=party(['dps','tank','healer','tank','healer','dps']);s.players.forEach(p=>p.dice=12);const draft=settled(s,random(53));assert.deepEqual(draft.queue.map(id=>effectiveRole(draft.players.find(p=>p.id===id))),['tank','tank','healer','healer','dps','dps']);assert.equal(draft.ties.groups.length,3);});
test('the largest configurable 32-player tie remains recoverable from a save',()=>{const s=party(Array(32).fill('dps'));s.players.forEach(p=>p.dice=11);for(let i=10;i<=32;i++)s.classes.push({id:'custom'+i,name:'Class '+i,roles:['dps'],enabled:true,color:'#a8c9cf'});const draft=startDraft(s,random(934));assert.equal(draft.ties.matches.filter(m=>m.winnerId).length,496);assert.deepEqual(parseSave(JSON.stringify(draft)),draft);});
test('all feasible standard role-count combinations complete over 20 random paths each',()=>{let paths=0;for(let tank=0;tank<=3;tank++)for(let healer=0;healer<=4;healer++)for(let dps=0;dps<=9;dps++){if(!tank&&!healer&&!dps||tank+healer+dps>9)continue;const s=party([...Array(tank).fill('tank'),...Array(healer).fill('healer'),...Array(dps).fill('dps')]);if(!brute(s.players,s.classes))continue;assert.equal(setupErrors(s,true).length,0);for(let seed=1;seed<=20;seed++){let next=settled(s,random(seed));while(next.phase!=='results'){const pool=spinPool(next);assert.ok(pool.safe.length);next=finishSpin(beginSpin(next,random(seed+next.picks.length)));}assert.equal(new Set(next.picks.map(p=>p.classId)).size,s.players.length);for(const pick of next.picks)assert.ok(s.classes.find(c=>c.id===pick.classId).roles.includes(effectiveRole(s.players.find(p=>p.id===pick.playerId))));paths++;}}assert.ok(paths>1000);});
test('matching agrees with independent exhaustive assignment for every enabled-class subset',()=>{for(let mask=0;mask<512;mask++)for(const roles of [['tank','healer'],['tank','tank','healer'],['healer','healer','dps'],['tank','tank','healer','healer']]){const s=party(roles);s.classes.forEach((c,i)=>c.enabled=!!(mask&(1<<i)));assert.equal(canAssign(s.players,s.classes),brute(s.players,s.classes),`${mask}: ${roles}`);}});
test('new draft keeps party and pools but clears rolls, tournament, pending and picks',()=>{let s=settled(party(['tank','healer']));s=finishSpin(beginSpin(s,()=>0));const next=editSetup(s);assert.equal(next.phase,'setup');assert.equal(next.players[0].name,s.players[0].name);assert.deepEqual(next.classes,s.classes);assert.ok(next.players.every(p=>p.dice===null));assert.deepEqual(next.picks,[]);assert.deepEqual(next.queue,[]);assert.equal(next.ties,null);assert.equal(next.pending,null);});
test('saves restore settled drafts exactly and pending spins recover the same one pick',()=>{const s=beginSpin(settled(party()),()=>1),storage={getItem:key=>key===SAVE_KEY?JSON.stringify(s):null};const restored=loadDraft(storage);assert.equal(restored.state.picks[0].classId,s.pending.classId);assert.equal(restored.state.picks.length,1);assert.equal(restored.state.pending,null);assert.match(restored.message,/interrupted spin/);assert.deepEqual(parseSave(JSON.stringify(restored.state)),restored.state);});
test('tournament reload preserves its original full order and all recorded draws',()=>{const s=party(Array(4).fill('dps'));s.players.forEach(p=>p.dice=10);let draft=startDraft(s,random(32));draft=advanceTie(draft);const restored=loadDraft({getItem:()=>JSON.stringify(draft)});assert.equal(restored.state.phase,'drafting');assert.deepEqual(restored.state.queue,draft.queue);assert.deepEqual(restored.state.ties.matches,draft.ties.matches);assert.match(restored.message,/interrupted tournament/);});
test('corrupt, future-version, impossible and inconsistent saved state are rejected and protected',()=>{for(const raw of ['not json',JSON.stringify({...newSetup(),version:99}),JSON.stringify({...newSetup(),phase:'results'})]){assert.throws(()=>parseSave(raw));assert.equal(loadDraft({getItem:()=>raw}).mode,'protected');}let s=settled(party(['dps','dps']));s=finishSpin(beginSpin(s,()=>0));s.picks.push({...s.picks[0],playerId:'p2'});assert.throws(()=>parseSave(JSON.stringify(s)));const tie=party(['dps','dps']);tie.players.forEach(p=>p.dice=6);const tampered=startDraft(tie,random(12));tampered.ties.matches[0].winnerId='stranger';assert.throws(()=>parseSave(JSON.stringify(tampered)));});
test('unavailable storage and quota errors remain playable, protected saves never overwrite',()=>{const blocked={getItem(){throw Error('blocked');},setItem(){throw Error('quota');}};assert.equal(loadDraft(blocked).mode,'memory');assert.equal(persistDraft(newSetup(),blocked).saved,false);let writes=0;const storage={setItem(){writes++;}};assert.equal(persistDraft(newSetup(),storage,true).saved,false);assert.equal(writes,0);assert.equal(persistDraft(newSetup(),storage).saved,true);assert.equal(writes,1);});
