import {test,expect}from'@playwright/test';import AxeBuilder from'@axe-core/playwright';import{mkdir}from'node:fs/promises';import{SAVE_KEY}from'../assets/save.js';
const travel=async(page,loc)=>{const button=page.locator(`[data-travel="${loc}"]`);if((await button.getAttribute('aria-current'))!=='page')await button.click();};
const action=(page,id)=>page.locator(`[data-action="${id}"]`).click();
async function finish(page,job,outcome){await travel(page,'square');await page.locator(`[data-job="${job}"]`).click();if(job==='bell'){await travel(page,'tower');await action(page,'inspect:bell');await travel(page,'marsh');await action(page,'inspect:nest');}if(job==='mill'){await travel(page,'mill');await action(page,'inspect:mill');if(outcome==='repair')await action(page,'inspect:toolbox');}if(job==='pie'){await travel(page,'inn');await action(page,'inspect:pie');await travel(page,'marsh');await action(page,'inspect:basket');}await action(page,`finish:${job}:${outcome}`);}
test('opening, acceptance, investigation and reload preserve choices',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('.notice-card')).toHaveCount(3);await page.locator('[data-job="bell"]').click();await travel(page,'tower');await action(page,'inspect:bell');await expect(page.locator('#event-title')).toHaveText('A missing clapper');await page.reload();await expect(page.locator('#event-title')).toHaveText('A missing clapper');await page.getByRole('button',{name:/Satchel/}).click();await expect(page.getByRole('dialog')).toContainText('Brass button');await page.keyboard.press('Escape');expect(errors).toEqual([]);});
for(const ending of [{bell:'gentle',mill:'repair',pie:'return'},{bell:'quiet',mill:'bargain',pie:'share'},{bell:'loud',mill:'force',pie:'sell'}]){
  test(`complete all three jobs in browser: ${Object.values(ending).join('/')}`,async({page})=>{await page.goto('/');for(const job of ['pie','bell','mill'])await finish(page,job,ending[job]);await expect(page.locator('#job-count')).toHaveText('3 / 3');await travel(page,'square');await action(page,'after:meeting');await expect(page.locator('#event-text')).toContainText('You came looking for work.');await travel(page,'inn');await action(page,'rest:morning');await expect(page.locator('#day-label')).toContainText('Day 2');await expect(page.locator('#job-count')).toHaveText('3 / 3');});
}
test('explicit reset requires confirmation and cancel preserves the story',async({page})=>{await page.goto('/');await page.locator('[data-job="mill"]').click();await page.getByRole('button',{name:'Save and adventure settings'}).click();await page.getByRole('button',{name:'Start a new adventure',exact:true}).click();await expect(page.getByText('Replace your current story?',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Keep my story'}).click();await page.keyboard.press('Escape');await expect(page.locator('[data-job="mill"]')).toContainText('Review clue');await page.getByRole('button',{name:'Save and adventure settings'}).click();await page.getByRole('button',{name:'Start a new adventure',exact:true}).click();await page.getByRole('button',{name:'Yes, start again'}).click();await expect(page.locator('[data-job="mill"]')).toContainText('Take this job');});
test('blocked storage remains playable and export works',async({page})=>{await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Blocked');}});});await page.goto('/');await page.locator('[data-job="pie"]').click();await expect(page.locator('#save-status')).toContainText('Not saved');await page.getByRole('button',{name:'Save and adventure settings'}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export your story'}).click();expect((await download).suggestedFilename()).toBe('briarwick-day-1.json');});
test('corrupt save is preserved and untrusted imported text does not execute',async({page})=>{await page.addInitScript(key=>localStorage.setItem(key,'not-json'),SAVE_KEY);await page.goto('/');await expect(page.locator('#save-status')).toContainText('will not be overwritten');await page.locator('[data-job="bell"]').click();expect(await page.evaluate(key=>localStorage.getItem(key),SAVE_KEY)).toBe('not-json');});
test('keyboard dialogs restore focus and all actions remain reachable',async({page})=>{await page.goto('/');const b=page.getByRole('button',{name:/Journal/});await b.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(b).toBeFocused();await page.locator('[data-job="bell"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#event-title')).toHaveText('A notice, taken');});
test('cross-tab update protects progress from accidental overwrite',async({page,context})=>{await page.goto('/');await page.locator('[data-job="bell"]').click();const other=await context.newPage();await other.goto('/');await other.locator('[data-job="pie"]').click();await expect(page.locator('#save-status')).toContainText('Another tab');await travel(page,'tower');await action(page,'inspect:bell');expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).jobs.pie.stage,SAVE_KEY)).toBe('active');});
test('import validates and requires confirmation before replacing story',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Save and adventure settings'}).click();await page.locator('#import-save').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.locator('#import-message')).toContainText('valid JSON');const saved=await page.evaluate(()=>({version:1,location:'inn',day:5,coins:4,kindness:0,firmness:0,wounded:false,items:[],clues:[],jobs:{bell:{stage:'posted',outcome:null},mill:{stage:'posted',outcome:null},pie:{stage:'posted',outcome:null}},flags:{introduced:false,bellGentled:false,millMended:false,pieAmends:false,fedNettle:false,meeting:false},journal:[],last:{title:'<img src=x onerror="window.bad=1">',body:'A harmless literal string.'},turns:0}));await page.locator('#import-save').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await expect(page.locator('#day-label')).toHaveText('Day 1');await page.getByRole('button',{name:'Load imported story'}).click();await expect(page.locator('#day-label')).toHaveText('Day 5');await expect(page.locator('#event-title')).toContainText('<img');expect(await page.evaluate(()=>window.bad)).toBeUndefined();});
for(const width of [360,390,768,1440])test(`responsive ${width}px and automated accessibility`,async({page})=>{await page.setViewportSize({width,height:960});await page.goto('/');await expect(page.locator('.notice-card')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations).toEqual([]);if(width===390||width===1440){await mkdir('artifacts',{recursive:true});await page.screenshot({path:`artifacts/briarwick-${width===390?'mobile':'desktop'}.png`,fullPage:true});}});
test('mobile can complete a job and review its changed town',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await finish(page,'bell','quiet');await travel(page,'square');await expect(page.locator('#notices')).toContainText('MORNINGS NOW BEGIN WHEN YOU ARE READY');await page.getByRole('button',{name:/Journal/}).click();const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations).toEqual([]);});
